<?php

namespace SoukElMedina\MagasinsBundle\Repository;

/**
 * MenuRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MagasinRepository extends \Doctrine\ORM\EntityRepository
{
    public function findProduitByMagasin($idmagasin){
        $query=$this->getEntityManager()->createQuery("
        select c from SoukElMedinaProduitBundle:Produits c 
        WHERE c.idmagasin LIKE :s ")->setParameter('s','%'.$idmagasin.'%');
        return $query->getResult();

    }}
