souk_el_medina_user_homepageclient:
    path:     /admin/userlist
    defaults: { _controller: SoukElMedinaUserBundle:AdminUser:index }

souk_el_medina_user_homepagevendeur:
    path:     /admin/vendeurlist
    defaults: { _controller: SoukElMedinaUserBundle:AdminUser:indexVendeur }

souk_el_medina_user_bloqueraction:
    path:     /admin/bloquerclient/{id}
    defaults: { _controller: SoukElMedinaUserBundle:AdminUser:BloquerClient }

souk_el_medina_user_activeraction:
    path:     /admin/activerclient/{id}
    defaults: { _controller: SoukElMedinaUserBundle:AdminUser:ActiverClient }

souk_el_medina_user_supprimeraction:
    path:     /admin/supprimerclient/{id}
    defaults: { _controller: SoukElMedinaUserBundle:AdminUser:supprimerClient }

souk_el_medina_user_confirmer_supprimeraction:
    path:     /admin/confirmersuppression/{id}
    defaults: { _controller: SoukElMedinaUserBundle:AdminUser:confirmSuppression }

souk_el_medina_user_annuler_supprimeraction:
    path:     /admin/annulersuppression
    defaults: { _controller: SoukElMedinaUserBundle:AdminUser:annulerSuppression }


