souk_el_medina_user_homepageclient:
    path:     /administrateur/userlist
    defaults: { _controller: SoukElMedinaUserBundle:AdminUser:index }

souk_el_medina_user_homepagevendeur:
    path:     /administrateur/vendeurlist
    defaults: { _controller: SoukElMedinaUserBundle:AdminUser:indexVendeur }

souk_el_medina_user_bloqueraction:
    path:     /administrateur/bloquerclient/{id}
    defaults: { _controller: SoukElMedinaUserBundle:AdminUser:BloquerClient }

souk_el_medina_user_activeraction:
    path:     /administrateur/activerclient/{id}
    defaults: { _controller: SoukElMedinaUserBundle:AdminUser:ActiverClient }

souk_el_medina_user_supprimeraction:
    path:     /administrateur/supprimerclient/{id}
    defaults: { _controller: SoukElMedinaUserBundle:AdminUser:supprimerClient }

souk_el_medina_user_confirmer_supprimeraction:
    path:     /administrateur/confirmersuppression/{id}
    defaults: { _controller: SoukElMedinaUserBundle:AdminUser:confirmSuppression }

souk_el_medina_user_annuler_supprimeraction:
    path:     /administrateur/annulersuppression
    defaults: { _controller: SoukElMedinaUserBundle:AdminUser:annulerSuppression }


