evenements_index_admin:
    path:     /
    defaults: { _controller: "SoukElMedinaEvenementBundle:Evenements:indexAdmin" }
    methods:  [GET,POST]
evenements_show_admin:
    path:     /{id}/show
    defaults: { _controller: "SoukElMedinaEvenementBundle:Evenements:showAdmin" }
    methods:  [GET,POST]
    options:
        expose: true
evenements_delete_admin:
    path:     /{idevenement}/delete
    defaults: { _controller: "SoukElMedinaEvenementBundle:Evenements:deleteAdmin" }
    options:
        expose: true
evenements_search_ajax:
    path:     /{name}/search
    defaults: { _controller: "SoukElMedinaEvenementBundle:Evenements:Search" }
    options:
        expose: true
evenements_accepter:
    path:     /{id}/accepter
    defaults: { _controller: "SoukElMedinaEvenementBundle:Evenements:Accepter"}
    options:
        expose: true

evenements_refuser:
    path:     /{id}/refuser
    defaults: { _controller: "SoukElMedinaEvenementBundle:Evenements:Refuser"}
    options:
        expose: true

evenements_demande:
    path:     /demande
    defaults: { _controller: "SoukElMedinaEvenementBundle:Evenements:Demande"}
    options:
        expose: true

evenements_search_ajax_request:
    path:     /{name}/searchRequest
    defaults: { _controller: "SoukElMedinaEvenementBundle:Evenements:SearchRequest" }
    options:
        expose: true

evenements_search_ajax_block:
    path:     /{name}/searchblock
    defaults: { _controller: "SoukElMedinaEvenementBundle:Evenements:SearchBlock" }
    options:
        expose: true
evenements_block:
    path:     /{id}/block
    defaults: { _controller: "SoukElMedinaEvenementBundle:Evenements:Block"}
    options:
        expose: true
evenements_Unlock:
    path:     /{id}/Unlock
    defaults: { _controller: "SoukElMedinaEvenementBundle:Evenements:Unlock"}
    options:
        expose: true
evenements_Listblock:
    path:     /listeblock
    defaults: { _controller: "SoukElMedinaEvenementBundle:Evenements:indexBlok"}
    options:
        expose: true