evenements_index:
    path:     /
    defaults: { _controller: "SoukElMedinaEvenementBundle:Evenements:index" }
    methods:  GET

evenements_show:
    path:     /{id}/show
    defaults: { _controller: "SoukElMedinaEvenementBundle:Evenements:show" }
    methods:  GET

evenements_new:
    path:     /new
    defaults: { _controller: "SoukElMedinaEvenementBundle:Evenements:new" }
    methods:  [GET, POST]

evenements_edit:
    path:     /{id}/edit
    defaults: { _controller: "SoukElMedinaEvenementBundle:Evenements:edit" }
    methods:  [GET, POST]

evenements_delete:
    path:     /{idevenement}/delete
    defaults: { _controller: "SoukElMedinaEvenementBundle:Evenements:delete" }
#    methods:  DELETE
affichermap:
    path:     /map/{long}/{lat}
    defaults: { _controller: "SoukElMedinaEvenementBundle:Evenements:affichermap"}
evenements_index_sub:
    path:     /Participant
    defaults: { _controller: "SoukElMedinaEvenementBundle:Evenements:indexParticipant" }
    methods:  [GET, POST]
evenements_index_sub_ev:
    path:     /{id}/Participant
    defaults: { _controller: "SoukElMedinaEvenementBundle:Evenements:indexParticipantevnt" }
    methods:  [GET, POST]
evenements_delete_sub:
    path:     /{idparticipant}/delete
    defaults: { _controller: "SoukElMedinaEvenementBundle:Evenements:deleteParticipant" }