magasins_index:
    path:     /
    defaults: { _controller: "SoukElMedinaPidevBundle:Magasins:index" }
    methods:  GET

magasins_show:
    path:     /{idmagasin}/show
    defaults: { _controller: "SoukElMedinaPidevBundle:Magasins:show" }
    methods:  GET

magasins_new:
    path:     /new
    defaults: { _controller: "SoukElMedinaPidevBundle:Magasins:new" }
    methods:  [GET, POST]

magasins_edit:
    path:     /{idmagasin}/edit
    defaults: { _controller: "SoukElMedinaPidevBundle:Magasins:edit" }
    methods:  [GET, POST]

magasins_delete:
    path:     /{idmagasin}/delete
    defaults: { _controller: "SoukElMedinaPidevBundle:Magasins:delete" }
    methods:  DELETE
