produits_index:
    path:     /
    defaults: { _controller: "SoukElMedinaPidevBundle:Produits:index" }
    methods:  GET

produits_show:
    path:     /{idproduit}/show
    defaults: { _controller: "SoukElMedinaPidevBundle:Produits:show" }
    methods:  GET

produits_new:
    path:     /new
    defaults: { _controller: "SoukElMedinaPidevBundle:Produits:new" }
    methods:  [GET, POST]

produits_edit:
    path:     /{idproduit}/edit
    defaults: { _controller: "SoukElMedinaPidevBundle:Produits:edit" }
    methods:  [GET, POST]

produits_delete:
    path:     /{idproduit}/delete
    defaults: { _controller: "SoukElMedinaPidevBundle:Produits:delete" }
    #methods:  DELETE
maxprix:
    path:     /maxprix/{prix}
    defaults: { _controller: "SoukElMedinaPidevBundle:Produits:RechercheParPrix" }
    methods:  [GET, POST]