promotions_index:
    path:     /
    defaults: { _controller: "SoukElMedinaPidevBundle:Promotions:index" }
    methods:  GET

promotions_show:
    path:     /{idpromotion}/show
    defaults: { _controller: "SoukElMedinaPidevBundle:Promotions:show" }
    methods:  GET

promotions_new:
    path:     /new
    defaults: { _controller: "SoukElMedinaPidevBundle:Promotions:new" }
    methods:  [GET, POST]

promotions_edit:
    path:     /{idpromotion}/edit
    defaults: { _controller: "SoukElMedinaPidevBundle:Promotions:edit" }
    methods:  [GET, POST]

promotions_delete:
    path:     /{idpromotion}/delete
    defaults: { _controller: "SoukElMedinaPidevBundle:Promotions:delete" }
    methods:  DELETE
