services:
#    souk_el_medina_panier.example:
#        class: SoukElMedina\PanierBundle\Example
#        arguments: ["@service_id", "plain_value", "%parameter%"]



     souk_el_medina_panier_process_service:
         class: SoukElMedina\PanierBundle\Controller\PanierController




